name: Publish drive-sync

on:
  push:
    tags:
      - 'drive-sync-v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read
  
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm -w packages/drive-sync run build
      - run: npm -w packages/drive-sync run test
      - run: npm publish --access public --provenance --workspace packages/drive-sync
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
